/**
 * Confirmed-NOISE denylist. Companies here were REMOVED from the registry
 * (formerly config/companies.json, now the Companies tab) because they meet
 * the strict noise bar (see docs/superpowers/plans/2026-06-19-
 * registry-expansion-denoise-categorize.md §9): they (i) never hire tech in India
 * and never will, (ii) are not a tech employer at all, or are defunct / mis-seeded
 * / exact duplicates. `isDeniedCompany` checks this so the discovery queue can
 * NEVER re-add them. Keyed by the exact `source_slug` the company had.
 *
 * Each removal is researched + confirmed by hand (web + curl), not by telemetry.
 * Grows one denoise wave at a time. Low/zero scrape yield is NOT grounds for entry.
 */
export const NOISE_DENYLIST_SLUGS: Record<string, string> = {
  // Wave 1 (2026-06-19)
  "lifestyle-international-india": "exact duplicate of lifestyle-international",
  "frapper": "DNS-dead (frapper.in unresolvable); mis-seed, likely typo of Frappe",
  "bharat-ai": "DNS-dead (bharatai.in unresolvable); unverifiable, mis-seed",
  "falcon-ai": "DNS-dead; investment firm, not a tech employer",
  "greenbloks": "DNS-dead; rebranded to an Iceland infra co, no India presence",
  "hyperkraft": "DNS-dead; no India tech presence, mis-seed",
  "entrackr": "startup-news media outlet — does not hire tech roles",
  "leadingx": "Austrian coaching/training consultancy — not India, not a tech product co",
  "lazy-ai": "US-only (Wilmington, DE); no India hiring",
  // Wave 2 (2026-06-19)
  "blinkit": "does not hire publicly — no public careers board (darwinbox tenant errors on jobs API)",
  "grofers": "old name of Blinkit — no public hiring board",
  // Wave 3 (2026-06-19): evidence-checked - no evidence of EVER hiring SWE or data/SQL roles in India (or defunct/non-India/malformed)
  "atomicindustries": "no SWE/data-hiring evidence 2026-06-19 (Atomic Industries)",
  "abg-shipyard": "no SWE/data-hiring evidence 2026-06-19 (ABG Shipyard)",
  "aeropay": "no SWE/data-hiring evidence 2026-06-19 (AeroPay)",
  "anveya": "no SWE/data-hiring evidence 2026-06-19 (Anveya)",
  "atlas-skilltech": "no SWE/data-hiring evidence 2026-06-19 (Atlas SkillTech)",
  "aukera-diamonds": "no SWE/data-hiring evidence 2026-06-19 (Aukera Diamonds)",
  "bajaj-holdings": "no SWE/data-hiring evidence 2026-06-19 (Bajaj Holdings)",
  "beardo": "no SWE/data-hiring evidence 2026-06-19 (Beardo)",
  "boldfit": "no SWE/data-hiring evidence 2026-06-19 (Boldfit)",
  "bombay-hemp-company": "no SWE/data-hiring evidence 2026-06-19 (Bombay Hemp Company)",
  "business-analyst-chennai-bright-river-careers-recruitee": "no SWE/data-hiring evidence 2026-06-19 (Business Analyst - Chennai - bright river careers )",
  "carbon-crusader": "no SWE/data-hiring evidence 2026-06-19 (Carbon Crusader)",
  "cellogen-therapeutics": "no SWE/data-hiring evidence 2026-06-19 (Cellogen Therapeutics)",
  "climate-pledge-india": "no SWE/data-hiring evidence 2026-06-19 (Climate Pledge India)",
  "core": "no SWE/data-hiring evidence 2026-06-19 (CORE)",
  "eilla-ai": "no SWE/data-hiring evidence 2026-06-19 (Eilla AI)",
  "factoryos": "no SWE/data-hiring evidence 2026-06-19 (FactoryOS)",
  "heyday": "no SWE/data-hiring evidence 2026-06-19 (Heyday)",
  "hrx": "no SWE/data-hiring evidence 2026-06-19 (HRX)",
  "ideaforge-s-board-greenlights-plans-to": "no SWE/data-hiring evidence 2026-06-19 (ideaForge’s Board Greenlights Plans To)",
  "innov8": "no SWE/data-hiring evidence 2026-06-19 (Innov8)",
  "khethworks": "no SWE/data-hiring evidence 2026-06-19 (Khethworks)",
  "loka-living": "no SWE/data-hiring evidence 2026-06-19 (Loka Living)",
  "mahindra-lifespace": "no SWE/data-hiring evidence 2026-06-19 (Mahindra Lifespace)",
  "mokobara": "no SWE/data-hiring evidence 2026-06-19 (MOKOBARA)",
  "mypetrolpump": "no SWE/data-hiring evidence 2026-06-19 (MyPetrolPump)",
  "pay-swifter": "no SWE/data-hiring evidence 2026-06-19 (Pay Swifter)",
  "petstop": "no SWE/data-hiring evidence 2026-06-19 (Petstop)",
  "phab": "no SWE/data-hiring evidence 2026-06-19 (Phab)",
  "phool": "no SWE/data-hiring evidence 2026-06-19 (Phool)",
  "physis-capital-announces-final": "no SWE/data-hiring evidence 2026-06-19 (Physis Capital announces final)",
  "plastics-for-change": "no SWE/data-hiring evidence 2026-06-19 (Plastics for Change)",
  "plum-goodness": "no SWE/data-hiring evidence 2026-06-19 (Plum Goodness)",
  "pomp-cosmetics": "no SWE/data-hiring evidence 2026-06-19 (Pomp Cosmetics)",
  "product-analyst": "no SWE/data-hiring evidence 2026-06-19 (Product Analyst)",
  "python-developer-remote-monks": "no SWE/data-hiring evidence 2026-06-19 (Python Developer (Remote) | Monks)",
  "recurrent-ventures": "no SWE/data-hiring evidence 2026-06-19 (Recurrent Ventures)",
  "regional-partner-manager-india-wiz": "no SWE/data-hiring evidence 2026-06-19 (Regional Partner Manager - India | Wiz)",
  "sedemac-s-strong-q4-cellogen": "no SWE/data-hiring evidence 2026-06-19 (SEDEMAC’s Strong Q4, Cellogen)",
  "senior-accounting-specialist-chennai-tamil-nadu-india": "no SWE/data-hiring evidence 2026-06-19 (Senior Accounting Specialist - Chennai, Tamil Nadu)",
  "sennheiser-india": "no SWE/data-hiring evidence 2026-06-19 (Sennheiser India)",
  "slurrp-farm": "no SWE/data-hiring evidence 2026-06-19 (Slurrp Farm)",
  "sr-it-automation-engineer-remote-india": "no SWE/data-hiring evidence 2026-06-19 (Sr. IT Automation Engineer - Remote - India)",
  "the-man-company": "no SWE/data-hiring evidence 2026-06-19 (Helios Lifestyle (Emami-owned))",
  "tiea-connectors": "no SWE/data-hiring evidence 2026-06-19 (Tiea Connectors)",
  "treehouse-india": "no SWE/data-hiring evidence 2026-06-19 (Treehouse India)",
  "vanguard-marks-down-ola-agilitas": "no SWE/data-hiring evidence 2026-06-19 (Vanguard Marks Down Ola, Agilitas)",
  "victorops-india": "no SWE/data-hiring evidence 2026-06-19 (VictorOps India)",
  "voltas-beko": "no SWE/data-hiring evidence 2026-06-19 (Voltas Beko)",
  "wickedgud": "no SWE/data-hiring evidence 2026-06-19 (WickedGud)",
  "wow-tea": "no SWE/data-hiring evidence 2026-06-19 (Wow Tea)",
  "xyxx": "no SWE/data-hiring evidence 2026-06-19 (XYXX)",
  "levitate": "no SWE/data-hiring evidence 2026-06-19 (Levitate)",
  // Wave 3b: name-kebab variants (re-discovery guard)
  "atomic-industries": "no SWE/data-hiring evidence 2026-06-19 (Atomic Industries)",
  "helios-lifestyle-emami-owned": "no SWE/data-hiring evidence 2026-06-19 (Helios Lifestyle (Emami-owned))",
  // Wave 4 (2026-06-19): full-registry evidence sweep - no evidence of EVER hiring SWE/data in India (foreign/no-India, defunct, non-existent, non-tech)
  "browse.ai": "no India SWE/data evidence 2026-06-19 (Browse.ai India)",
  "browse-ai-india": "no India SWE/data evidence 2026-06-19 (Browse.ai India)",
  "coinflow": "no India SWE/data evidence 2026-06-19 (Coinflow)",
  "drata": "no India SWE/data evidence 2026-06-19 (Drata India)",
  "drata-india": "no India SWE/data evidence 2026-06-19 (Drata India)",
  "linear": "no India SWE/data evidence 2026-06-19 (Linear)",
  "mural": "no India SWE/data evidence 2026-06-19 (Mural India)",
  "mural-india": "no India SWE/data evidence 2026-06-19 (Mural India)",
  "primer": "no India SWE/data evidence 2026-06-19 (Primer)",
  "scribe": "no India SWE/data evidence 2026-06-19 (Scribe)",
  "sequence": "no India SWE/data evidence 2026-06-19 (Sequence Finance)",
  "sequence-finance": "no India SWE/data evidence 2026-06-19 (Sequence Finance)",
  "vanta": "no India SWE/data evidence 2026-06-19 (Vanta India)",
  "vanta-india": "no India SWE/data evidence 2026-06-19 (Vanta India)",
  "vellum": "no India SWE/data evidence 2026-06-19 (Vellum AI)",
  "vellum-ai": "no India SWE/data evidence 2026-06-19 (Vellum AI)",
  "whippy": "no India SWE/data evidence 2026-06-19 (Whippy)",
  "aceflo": "no India SWE/data evidence 2026-06-19 (Aceflo)",
  "bee-ai": "no India SWE/data evidence 2026-06-19 (Bee.ai)",
  "bharatagri": "no India SWE/data evidence 2026-06-19 (BharatAgri)",
  "bueno-finance": "no India SWE/data evidence 2026-06-19 (Bueno Finance)",
  "cognigy-india": "no India SWE/data evidence 2026-06-19 (Cognigy India)",
  "crazy-egg-india": "no India SWE/data evidence 2026-06-19 (Crazy Egg India)",
  "drag-app": "no India SWE/data evidence 2026-06-19 (Drag App)",
  "ekam-health": "no India SWE/data evidence 2026-06-19 (Ekam Health)",
  "enerjazz": "no India SWE/data evidence 2026-06-19 (Enerjazz)",
  "indify": "no India SWE/data evidence 2026-06-19 (Indify)",
  "infinity": "no India SWE/data evidence 2026-06-19 (Infinity)",
  "invision-india": "no India SWE/data evidence 2026-06-19 (InVision India)",
  "leadiq": "no India SWE/data evidence 2026-06-19 (LeadIQ)",
  "loyalty-programs-pvt": "no India SWE/data evidence 2026-06-19 (Loyalty Programs Pvt)",
  "mantis-ai": "no India SWE/data evidence 2026-06-19 (Mantis AI)",
  "mira-ai-tutor": "no India SWE/data evidence 2026-06-19 (Mira AI Tutor)",
  "nearu": "no India SWE/data evidence 2026-06-19 (NearU)",
  "octane-ai": "no India SWE/data evidence 2026-06-19 (Octane AI)",
  "ola-earth-mission": "no India SWE/data evidence 2026-06-19 (Ola Earth Mission)",
  "preset-io-india": "no India SWE/data evidence 2026-06-19 (Preset.io India)",
  "quill-ai": "no India SWE/data evidence 2026-06-19 (Quill AI)",
  "sett-pay": "no India SWE/data evidence 2026-06-19 (Sett Pay)",
  "sindhuja-microcredit": "no India SWE/data evidence 2026-06-19 (Sindhuja Microcredit)",
  "skillshare-india": "no India SWE/data evidence 2026-06-19 (Skillshare India)",
  "spenny": "no India SWE/data evidence 2026-06-19 (Spenny)",
  "spinach-ai": "no India SWE/data evidence 2026-06-19 (Spinach.ai)",
  "stoa-school": "no India SWE/data evidence 2026-06-19 (Stoa School)",
  "streak": "no India SWE/data evidence 2026-06-19 (Streak)",
  "subtl-ai": "no India SWE/data evidence 2026-06-19 (Subtl.ai)",
  "tradier-india": "no India SWE/data evidence 2026-06-19 (Tradier India)",
  "wallit": "no India SWE/data evidence 2026-06-19 (Wallit)",
  "wforce": "no India SWE/data evidence 2026-06-19 (Wforce)",
  "wrogn": "no India SWE/data evidence 2026-06-19 (WROGN)",
  "airtable": "no India SWE/data evidence 2026-06-19 (Airtable India)",
  "airtable-india": "no India SWE/data evidence 2026-06-19 (Airtable India)",
  "boxinc": "no India SWE/data evidence 2026-06-19 (Box India)",
  "box-india": "no India SWE/data evidence 2026-06-19 (Box India)",
  "discord": "no India SWE/data evidence 2026-06-19 (Discord)",
  "hextechnologies": "no India SWE/data evidence 2026-06-19 (Hex India)",
  "hex-india": "no India SWE/data evidence 2026-06-19 (Hex India)",
  "pinterest": "no India SWE/data evidence 2026-06-19 (Pinterest)",
  "pinwheelapi": "no India SWE/data evidence 2026-06-19 (Pinwheel Pay)",
  "pinwheel-pay": "no India SWE/data evidence 2026-06-19 (Pinwheel Pay)",
  "trase": "no India SWE/data evidence 2026-06-19 (Trase AI)",
  "trase-ai": "no India SWE/data evidence 2026-06-19 (Trase AI)",
  "contentsquare": "no India SWE/data evidence 2026-06-19 (Heap Analytics India)",
  "heap-analytics-india": "no India SWE/data evidence 2026-06-19 (Heap Analytics India)",
  "skillshare": "no India SWE/data evidence 2026-06-19 (Skillshare India)",
  "ngc": "no India SWE/data evidence 2026-06-19 (Northrop Grumman India)",
  "northrop-grumman-india": "no India SWE/data evidence 2026-06-19 (Northrop Grumman India)",
  "reply-io-india": "no India SWE/data evidence 2026-06-19 (Reply.io India)",
  // Wave 5 (2026-07-01): broken-companies repair - confirmed defunct / acquired / parked domain
  "camp-k12": "defunct - edtech shut down (confirmed 2026-06-05, still dead 2026-07-01)",
  "waycool-foods": "defunct - WayCool under NCLT insolvency; careers.waycool.in dead",
  "trell": "defunct - social-commerce app shut down; trell.co careers dead",
  "locale-ai": "defunct - locale.ai unresolvable/dead",
  "marketo-india": "acquired by Adobe; hires via Adobe India (workday ats-api) - exact dup",
  "mfine-acquired-by-lifecell": "Mfine acquired by LifeCell; careers.lifecell.in dead (ECONNREFUSED)",
  "playment": "acquired by TELUS International; playment.io redirects to telusinternational.com",
  "mech-mocha": "defunct - mechmocha.com domain parked for sale (hugedomains.com)",
  "yenmo": "defunct - yenmo.com domain parked for sale (hugedomains.com)",
  "retape": "defunct - retape.com domain parked for sale (hugedomains.com)",
  "nykaa-fashion": "exact duplicate of nykaa (both careers URLs redirect to nykaa.com/who_are_we)",
  // Wave 6 (2026-07-01): broken-repair research pass - confirmed defunct/acquired/mis-seed
  "better-opinions": "defunct - prediction market shut down 2023",
  "edyst": "defunct - edtech platform discontinued (shutdown notice on site)",
  "able": "acquired by Instawork (Aug 2024); no own careers board",
  "cradle": "Cradle Finance (India) dormant/dead - ~2 employees, domain unresolvable",
  "digi-prex": "domain parked for sale (hugedomains.com) - defunct",
  "sigmamind-ai": "DNS-dead obscure micro-startup (mis-seed)",
  "slidely-ai": "DNS-dead obscure micro-startup (mis-seed)",
  "rehook-ai": "DNS-dead obscure micro-startup (mis-seed)",
  "rivia-ai": "DNS-dead obscure micro-startup (mis-seed)",
  "superapi": "DNS-dead obscure micro-startup (mis-seed)",
  "swadesi-way": "DNS-dead obscure micro-startup (mis-seed)",
  "tilt": "DNS-dead junk domain (mis-seed)",
};

/** True if this slug is on the confirmed-noise denylist. */
export function isNoiseSlug(slug: string): boolean {
  return Object.prototype.hasOwnProperty.call(NOISE_DENYLIST_SLUGS, slug.toLowerCase());
}
