/** Aggregators, content sites, and salary-blog SEO farms to skip during discovery. */
export const SKIP_HOSTS = [
  "linkedin.com", "indeed.com", "naukri.com", "glassdoor.com", "glassdoor.co.in",
  "monster.com", "ziprecruiter.com", "simplyhired.com", "ambitionbox.com",
  "shine.com", "timesjobs.com", "instahyre.com", "hirist.com", "iimjobs.com",
  "foundit.in", "wellfound.com", "angel.co", "builtin.com",
  "unojobs.com", "freshersworld.com", "joberge.com", "jobsforher.com",
  "jobaaj.com", "hireperfect.com", "jooble.org", "talent.com",
  "lsvp.com", "sequoiacap.com", "a16z.com", "accel.com",
  "kleinerperkins.com", "ycombinator.com",
  "youtube.com", "facebook.com", "twitter.com", "x.com", "instagram.com",
  "github.com", "medium.com", "substack.com", "reddit.com", "quora.com",
  "wikipedia.org", "crunchbase.com", "tracxn.com", "owler.com",
  "timesofindia.indiatimes.com", "indiatimes.com", "ndtv.com", "yourstory.com",
  "inc42.com", "entrackr.com", "moneycontrol.com", "livemint.com",
  "upgrad.com", "guvi.in", "igmguru.com", "excelgoodies.in", "edureka.co",
  "simplilearn.com", "intellipaat.com", "datacamp.com", "kaggle.com",
  "riadataanalytics.com", "growai.in", "analyticsvidhya.com",
  "geeksforgeeks.org", "tutorialspoint.com", "javatpoint.com",
] as const;

/** Rotating Brave search queries — daily run picks a subset by hash-of-date.
 *  Tune for your region and target role family. */
export const QUERY_POOL = [
  'site:boards.greenhouse.io "India"',
  'site:boards.greenhouse.io "Bangalore"',
  'site:boards.greenhouse.io "Bengaluru"',
  'site:boards.greenhouse.io "Mumbai" "analyst"',
  'site:boards.greenhouse.io "analyst" "India"',
  'site:job-boards.greenhouse.io "India"',
  'site:jobs.lever.co "India"',
  'site:jobs.lever.co "Bangalore"',
  'site:jobs.lever.co "Bengaluru" "analyst"',
  'site:jobs.ashbyhq.com "India"',
  'site:jobs.ashbyhq.com "Bangalore"',
  'site:careers.smartrecruiters.com "India"',
  'site:jobs.smartrecruiters.com "Bangalore"',
  'site:myworkdayjobs.com "India" "analyst"',
  'site:myworkdayjobs.com "Bangalore" "analytics"',
  'site:myworkdayjobs.com "Mumbai" "analyst"',
  'site:eightfold.ai "Bangalore"',
  'site:eightfold.ai "India" "analyst"',
  'site:apply.workable.com "India"',
  'site:apply.workable.com "Bangalore"',
  'site:recruitee.com "India" "analyst"',
  'inurl:/careers "Bengaluru" "data analyst" -site:linkedin.com -site:naukri.com',
  'inurl:/careers "Pune" "business analyst" -site:linkedin.com -site:naukri.com',
  'inurl:/careers "Mumbai" "analyst" -site:linkedin.com -site:naukri.com',
  'inurl:/careers "Hyderabad" "analyst" -site:linkedin.com -site:naukri.com',
  'inurl:careers. "Bangalore" "analytics" -inurl:salary -inurl:blog -inurl:course',
  'inurl:jobs. "Bengaluru" "analyst" -inurl:salary -inurl:blog -inurl:course',
] as const;
