import { test } from "node:test";
import assert from "node:assert/strict";
import { z } from "zod";
import { atsHttpError, atsFetchHtml, atsFetchText, atsFetchJson, parseOrThrow, parseOrNull } from "../http.js";
import { stubFetch, jsonResponse, CHALLENGE_PAGE_HTML } from "./testHelpers.js";
import {
  startConnectivityMonitor,
  stopConnectivityMonitor,
  connectivityStatus,
} from "../../util/connectivity.js";
import { isInfrastructureFault } from "../../util/errorCause.js";

test("atsHttpError: 404 gives a short provider-tagged message", () => {
  const e = atsHttpError("keka", 404, "<html>not found</html>");
  assert.equal(e.message, "keka 404");
});

test("atsHttpError: non-404 includes status and a trimmed body snippet", () => {
  const e = atsHttpError("oracle", 500, "x".repeat(500));
  assert.match(e.message, /^oracle HTTP 500: x+$/);
  assert.ok(e.message.length < 230, "body snippet should be capped at ~200 chars");
});

test("atsHttpError builds 404 and generic errors", () => {
  assert.equal(atsHttpError("phenom", 404, "x").message, "phenom 404");
  assert.match(atsHttpError("phenom", 500, "boom").message, /phenom HTTP 500: boom/);
});

test("atsFetchHtml returns the response body, falling back to the requested URL when res.url is empty", async (t) => {
  // Response's .url is read-only (populated by real fetch), so this exercises the res.url || url fallback.
  stubFetch(t, async () => new Response("<html>hi</html>", { status: 200 }));
  const { html, finalUrl } = await atsFetchHtml("https://example.com/careers", { provider: "phenom" });
  assert.equal(html, "<html>hi</html>");
  assert.equal(finalUrl, "https://example.com/careers");
});

test("atsFetchHtml throws atsHttpError on a non-OK response", async (t) => {
  stubFetch(t, async () => new Response("not found", { status: 404 }));
  // eslint-disable-next-line @typescript-eslint/no-restricted-types -- a caught/thrown value is `unknown` in TS by design (Standard rule 3)
  await assert.rejects(atsFetchHtml("https://example.com/careers", { provider: "keka" }), (err: unknown) => {
    assert.ok(err instanceof Error);
    assert.equal(err.message, "keka 404");
    return true;
  });
});

// atsHttpError keeps only 200 chars of body, truncating before WAF markers - the full body must be scanned for challenge evidence before the snippet is cut.
test("a non-OK response whose body is a WAF block page throws an edge-refusal error, not a board defect", async (t) => {
  const cloudFrontBody =
    `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n` +
    `<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n` +
    `<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>403 ERROR</H1>\n` +
    `<H2>The request could not be satisfied.</H2>\nRequest blocked.\n<PRE>\n` +
    `Generated by cloudfront (CloudFront)\nRequest ID: 8skGKzMvyeMU==\n</PRE>\n</BODY></HTML>`;
  stubFetch(t, async () => new Response(cloudFrontBody, { status: 403 }));
  // eslint-disable-next-line @typescript-eslint/no-restricted-types -- a caught/thrown value is `unknown` in TS by design (Standard rule 3)
  await assert.rejects(atsFetchJson("https://careers.example/api/pcsx/search", { provider: "eightfoldpcs" }), (err: unknown) => {
    assert.ok(err instanceof Error);
    assert.match(err.message, /an edge refused the request/);
    assert.ok(isInfrastructureFault(err), "must classify as infrastructure so the row is never charged");
    return true;
  });
});

test("a non-OK response with a plain body still throws the ordinary HTTP status error", async (t) => {
  stubFetch(t, async () => new Response("permission denied for this endpoint", { status: 403 }));
  // eslint-disable-next-line @typescript-eslint/no-restricted-types -- a caught/thrown value is `unknown` in TS by design (Standard rule 3)
  await assert.rejects(atsFetchJson("https://careers.example/api", { provider: "workday" }), (err: unknown) => {
    assert.ok(err instanceof Error);
    assert.equal(err.message, "workday HTTP 403: permission denied for this endpoint");
    assert.equal(isInfrastructureFault(err), false, "a plain 403 is the board's answer and stays chargeable");
    return true;
  });
});

test("atsFetchText is a thin wrapper that discards finalUrl", async (t) => {
  stubFetch(t, async () => new Response("plain text body", { status: 200 }));
  const text = await atsFetchText("https://example.com/careers", { provider: "keka" });
  assert.equal(text, "plain text body");
});

// withAtsTimeout's default duration is untestable without config injection; these two tests pin what is pinnable: the signal reaches fetch, and abort propagates.
test("atsFetchJson passes an abortable timeout signal to fetch", async (t) => {
  let sawSignal = false;
  stubFetch(t, (_url, init) => {
    sawSignal = init?.signal instanceof AbortSignal;
    return Promise.resolve(jsonResponse({}));
  });
  await atsFetchJson("https://x.example/api");
  assert.equal(sawSignal, true);
});

test("atsFetchJson rejects when fetch rejects with an AbortError (timeout signal fired)", async (t) => {
  stubFetch(t, () => Promise.reject(new DOMException("This operation was aborted", "AbortError")));
  await assert.rejects(atsFetchJson("https://x.example/api"), /abort/i);
});

test("parseOrThrow returns the typed value on success", () => {
  const S = z.object({ a: z.number() });
  assert.deepEqual(parseOrThrow(S, { a: 1 }, { provider: "x", slug: "acme" }), { a: 1 });
});
test("parseOrThrow throws with provider/slug and 'schema' in the message on mismatch", () => {
  const S = z.object({ a: z.number() });
  assert.throws(() => parseOrThrow(S, { a: "no" }, { provider: "x", slug: "acme", what: "list" }),
    /x list response failed schema for acme/);
});
test("parseOrNull returns null on mismatch", () => {
  const S = z.object({ a: z.number() });
  assert.equal(parseOrNull(S, { a: "no" }, { provider: "x", slug: "acme" }), null);
});

// The whole gate exists so a board fetch WAITS out an outage instead of failing and letting the run march on.
test("atsFetchJson waits out a network outage instead of failing the board", async (t) => {
  let online = false;
  t.after(stopConnectivityMonitor);
  startConnectivityMonitor({ intervalMs: 5, downIntervalMs: 5, probe: async () => online });
  await new Promise((r) => setTimeout(r, 20));

  let fetchCalls = 0;
  stubFetch(t, async () => {
    fetchCalls++;
    return jsonResponse({ ok: true });
  });

  let settled = false;
  const pending = atsFetchJson("https://boards.example/jobs").then((v) => {
    settled = true;
    return v;
  });

  await new Promise((r) => setTimeout(r, 30));
  assert.equal(fetchCalls, 0, "must not have touched the network while it was down");
  assert.equal(settled, false, "must still be waiting, not skipped");

  online = true;
  const result = await pending;
  assert.equal(fetchCalls, 1, "resumed exactly once, after recovery");
  assert.deepEqual(result, { ok: true });
});

// A board that answers, even with a block page, proves the connection is fine, so one hostile host must never pause everything else.
test("a blocked board reports success to the monitor and does not pause the run", async (t) => {
  t.after(stopConnectivityMonitor);
  startConnectivityMonitor({ intervalMs: 10_000, downIntervalMs: 10_000, probe: async () => true });
  await new Promise((r) => setTimeout(r, 15));

  stubFetch(t, async () => new Response("<html>Access Denied</html>", { status: 403 }));
  await assert.rejects(atsFetchJson("https://waf.example/jobs"));

  assert.equal(connectivityStatus().down, false, "a 403 is the board's problem, not the network's");
});

// Retry-After is clamped to a 250ms floor (util/httpRetry.ts), which is what keeps these fast enough to assert for real.
test("fetchOk retries a 429 with Retry-After then returns the 200 that follows", async (t) => {
  let calls = 0;
  stubFetch(t, async () => {
    calls++;
    if (calls === 1) return new Response("rate limited", { status: 429, headers: { "Retry-After": "0.25" } });
    return jsonResponse({ ok: true });
  });
  const result = await atsFetchJson("https://x.example/api", { provider: "acme" });
  assert.deepEqual(result, { ok: true });
  assert.equal(calls, 2);
});

test("fetchOk retries a retryable status up to the attempt cap, then throws with the last body", async (t) => {
  let calls = 0;
  stubFetch(t, async () => {
    calls++;
    return new Response(`server exploded on attempt ${calls}`, { status: 503, headers: { "Retry-After": "0.25" } });
  });
  // eslint-disable-next-line @typescript-eslint/no-restricted-types -- a caught/thrown value is `unknown` in TS by design (Standard rule 3)
  await assert.rejects(atsFetchJson("https://x.example/api", { provider: "acme" }), (err: unknown) => {
    assert.ok(err instanceof Error);
    assert.match(err.message, /server exploded on attempt 3/);
    return true;
  });
  assert.equal(calls, 3, "one original attempt plus two retries");
});

test("fetchOk does not retry a non-retryable status like 404", async (t) => {
  let calls = 0;
  stubFetch(t, async () => {
    calls++;
    return new Response("nope", { status: 404 });
  });
  await assert.rejects(atsFetchJson("https://x.example/api", { provider: "acme" }), /acme 404/);
  assert.equal(calls, 1);
});

// Edge-challenge classification must still fire off the FINAL attempt's body — it is what powers the deferred end-of-run retry pass.
test("fetchOk still classifies an edge challenge after exhausting retries", async (t) => {
  let calls = 0;
  stubFetch(t, async () => {
    calls++;
    return new Response(CHALLENGE_PAGE_HTML, { status: 503, headers: { "Retry-After": "0.25" } });
  });
  // eslint-disable-next-line @typescript-eslint/no-restricted-types -- a caught/thrown value is `unknown` in TS by design (Standard rule 3)
  await assert.rejects(atsFetchJson("https://x.example/api", { provider: "acme" }), (err: unknown) => {
    assert.ok(err instanceof Error);
    assert.match(err.message, /an edge refused the request/);
    assert.ok(isInfrastructureFault(err), "must classify as infrastructure so the row is never charged");
    return true;
  });
  assert.equal(calls, 3);
});
